### ISSUE TITLE
AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by kosayoda** [ColinDuquesnoy/QDarkStyleSheet#162]
### Language

Python

### Steps to Reproduce

1. Create new virtualenv `python3.7 -m venv .venv`
2. Install qdarkstyle `pip install qdarkstyle`
3. Run `qdarkstyle --all`

### Actual Result

```
(.venv) kosa@Mirage:~/Documents$ qdarkstyle --all
usage: qdarkstyle [-h] [-i] [-b] [-a] [-v] [--all]

optional arguments:
  -h, --help          show this help message and exit
  -i, --information   Show information about environment (important for bug
                      report)
  -b, --bindings      Show available bindings for Qt
  -a, --abstractions  Show available abstraction layers for Qt bindings
  -v, --version       Show qdarkstyle version
  --all               Show all information options at once

Information about your current environment setup:
  - QDarkStyle: 2.6.8
  - OS: Linux 4.15.0-48-generic x86_64
  - Platform: linux
  - Python: 3.7.2.final.0
  - Python API: 1013
  - Binding in use:     Not set or nonexistent
  - Abstraction in use: Not set or nonexistent
  - qtpy (QT_API):                Not set or nonexistent
  - pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
  - Qt.py (__binding__):          Not set or nonexistent
Traceback (most recent call last):
  File "/home/kosa/Documents/.venv/bin/qdarkstyle", line 11, in <module>
    sys.exit(main())
  File "/home/kosa/Documents/.venv/lib/python3.7/site-packages/qdarkstyle/__main__.py", line 47, in main
    info = qt_bindings()
  File "/home/kosa/Documents/.venv/lib/python3.7/site-packages/qdarkstyle/__init__.py", line 400, in qt_bindings
    return _check_imports(import_list=QT_BINDINGS)
  File "/home/kosa/Documents/.venv/lib/python3.7/site-packages/qdarkstyle/__init__.py", line 426, in _check_imports
    spec = importlib.util.find_spec(current_import)
AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by dpizetta** [comment]
I've marked as wontfix because we will start using helpdev to get this kind of info, and I already fixed this problem in the helpdev. It should be fixed in v2.7. Thanks for reporting.
