### ISSUE TITLE
tests fail with python 3.10

### ISSUE THREAD

**Issue by nonamedotc** [ColinDuquesnoy/QDarkStyleSheet#277]
### Describe Your Environment

Building qdarkstyle with fedora 35 (rawhide) and python 3.10 alpha

[Versions from your environment]

- QDarkStyle: 3.0.2
- OS: Linux (Fedora 35)
- Python: 3.10 alpha

### Language

Python

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

I am trying to build version 3.0.2 against python 3.10 alpha. Two of the tests fail due to changes in python 3.10.

Relevant python changes - https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-0-alpha-6

### Actual Result

```
utils (unittest.loader._FailedTest) ... ERROR
qdarkstyle.utils (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: utils
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/QDarkStyle-3.0.2/qdarkstyle/utils/__init__.py", line 18, in <module>
    from qdarkstyle.utils.scss import create_qss
  File "/builddir/build/BUILD/QDarkStyle-3.0.2/qdarkstyle/utils/scss.py", line 14, in <module>
    import qtsass
  File "/usr/lib/python3.10/site-packages/qtsass/__init__.py", line 14, in <module>
    from qtsass.api import compile, compile_filename, compile_dirname, watch
  File "/usr/lib/python3.10/site-packages/qtsass/api.py", line 13, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)


======================================================================
ERROR: qdarkstyle.utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: qdarkstyle.utils
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/QDarkStyle-3.0.2/qdarkstyle/utils/__init__.py", line 18, in <module>
    from qdarkstyle.utils.scss import create_qss
  File "/builddir/build/BUILD/QDarkStyle-3.0.2/qdarkstyle/utils/scss.py", line 14, in <module>
    import qtsass
  File "/usr/lib/python3.10/site-packages/qtsass/__init__.py", line 14, in <module>
    from qtsass.api import compile, compile_filename, compile_dirname, watch
  File "/usr/lib/python3.10/site-packages/qtsass/api.py", line 13, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

```

### Expected Results / Proposed Result

Expectation is that tests do not fail and package builds successfully.

**Comment by tirkarthi** [comment]
This was fixed in qtsass but seems to have not made it to a release : https://github.com/spyder-ide/qtsass/pull/54

**Comment by dalthviz** [comment]
Just in case, qtsass 0.3.1 was just released 🎉
